# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custreg', '0002_auto_20191119_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='aduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['username'],
                'verbose_name': '\u7ba1\u7406\u5458\u7528\u6237',
                'verbose_name_plural': '\u7ba1\u7406\u5458\u7528\u6237',
            },
        ),
    ]
