# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custreg', '0003_aduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('endTime', models.DateTimeField()),
                ('endReg', models.BooleanField()),
                ('hideCon', models.BooleanField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='conNum',
            field=models.IntegerField(default=0),
        ),
    ]
