# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-07 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custreg', '0004_auto_20200107_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='hideCon',
        ),
    ]
