# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('use_statime', models.IntegerField(default=0)),
                ('use_endtime', models.IntegerField(default=0)),
                ('use_course', models.IntegerField(default=0)),
                ('use_teacher', models.IntegerField(default=0)),
                ('use_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('tea_number', models.IntegerField(default=0)),
                ('tea_name', models.CharField(max_length=200)),
                ('sta_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
    ]
