# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-28 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='c_time',
        ),
    ]
