# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0002_auto_20191228_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
