# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0003_auto_20191228_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='use_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
