# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('option1', models.CharField(max_length=256)),
                ('option2', models.CharField(max_length=256)),
                ('option3', models.CharField(max_length=256)),
                ('option4', models.CharField(max_length=256)),
                ('question_type', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('username', models.CharField(max_length=128)),
            ],
        ),
    ]
