# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=256),
        ),
    ]
